### ISSUE TITLE
option to make notifications sticky

### ISSUE THREAD

**Issue by mihai-chezan** [mihai-chezan/owa_notifications_firefox_extension#1]
Allow the option to make notifications sticky (If I'm in a meeting and don't get back to my machine for a while the notifications go away)
see: https://addons.mozilla.org/en-US/firefox/addon/outlook-web-app-notifications/reviews/667912

**Comment by nilskp** [comment]
+1

**Comment by nilskp** [comment]
As part of #2 it would be great to be able to set for either. E.g. I would generally not want email notifications to be sticky, but really would like calendar notifications to be sticky.

**Comment by alesny** [comment]
There is a bug/enhancement in Firefox for this: https://bugzilla.mozilla.org/show_bug.cgi?id=875114
There is also a simple workaround for now: https://bugzilla.mozilla.org/show_bug.cgi?id=875114#c34

**Comment by mihai-chezan** [comment]
Thank you for those links. However I'm using [notifications](https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/notifications) API from Firefox not HTML5 Notifications.

Nevertheless, I'm thinking of replicating the functionality of OWA reminders, which if you hit snooze you get a new pop-up after 5 minutes (configurable) to remind you again about the calendar appointment. Only if you click Dismiss, the reminder will go away (and never come back).

So I'm thinking of this: 
1. we start with 0 reminders
2. reminder1 pops up -> notification
3. user doesn't react (no dismiss, no snooze)
4. after 5 minutes (configurable) show again the notification
5. repeat until the user acts on the reminder either by dismiss or snooze
6. user hits snooze
7. notification is not shown
8. OWA pop-up again the reminder after the user configured snooze period
9. notification is shown again
10. user doesn't react (no dismiss, no snooze)
11. after 5 minutes (configurable) show again the notification
12. repeat until the user acts on the reminder either by dismiss or snooze
13. user hits dimiss
14. notification is not shown anymore

**Comment by alesny** [comment]
It looks good. I would personally configure the delay to 4s instead of 5 minutes so it should stay sticky until I'll press dismiss or snooze.
Thanks.

**Comment by mihai-chezan** [comment]
Implementation for this feature: A new configurable property 'Reminder snooze time' was introduced with default value of 300 (5 minutes). What it does is when reminders are not dismissed/snoozed a reminder notification will keep showing up every 'Reminder snooze time' seconds. Set this to zero to disable it.". Set it to 4 or 5 to have the effect of sticky reminder notifications.
