### ISSUE TITLE
CSS for Outlook.com for Inbox Only

### ISSUE THREAD

**Issue by jscher2000** [mihai-chezan/owa_notifications_firefox_extension#11]
Hotmail/Live/Outlook users could use this extension in the new Office365-based Outlook.com, but may be put off by the count of unread across all folders. It currently seems to count even drafts and unread deleted items.

The following CSS works for Inbox only -- it probably could be simplified depending on what your code does: 

`span[title="Inbox"] + div>span`

Could I suggest adding something about this to your AMO listing? Users seeking a replacement for the old extensions that do not work on the new Outlook.com may not be able to write their own CSS. And providing a recipe could help avoid negative reviews if that matters to you.

https://support.mozilla.org/questions/1134685

**Comment by mihai-chezan** [comment]
Hi, 
Thank you for point this out and sorry for late reply.
I've updated the addon details on AMO to reflect this.

**Comment by jburrill** [comment]
I really find this Add-On helpful.  However, I follow the theme of others who would like more granularity in the alerts.  I have several folders within my Inbox.  I wish to see only those alerts for the Inbox proper, and not the folders within.  I cannot seem to find tweaks needed to do this with OWA for Exchange 2013.

**Comment by jburrill** [comment]
Wow!  Asked and answered.  Sorry for any concern.  I was able to narrow down to the element I needed and Firefox Developer Tools actually retrieved the CSS Selector for me:

#_ariaId_90 > div:nth-child(1) > div:nth-child(1) > div:nth-child(1) > span:nth-child(3)

That seems to do the trick (although I am awating an Exchange Rule to redirect a message to an Inbox folder to see if it is definitive enough to alert for only Inbox, and not fro my GitHub folder, for instance.

**Comment by katutxakurra** [comment]
That's useful, thanks. I wanted to receive notifications for all mails in my favourite folders, but not for Drafts. This worked so far:

    .treeHeaderContainer + [id="MailFolderPane.FavoritesFolders"] :not([Title='Drafts']) + div > span

**Comment by mihai-chezan** [comment]
Thank you for sharing.
