### ISSUE TITLE
Toggle to disable the popup system notification message when a new email is received

### ISSUE THREAD

**Issue by mihai-chezan** [mihai-chezan/owa_notifications_firefox_extension#12]
The ability to disable the popup system notification message when a new email is received. I really only need to see the count of new emails in the tab.

Suggested here: https://addons.mozilla.org/en-US/firefox/addon/outlook-web-app-notifications/reviews/821389/

**Comment by micgrivas** [comment]
Is there a way to disable the notification for emails?  I see it's pushed, but I see no config anywhere.

**Comment by mihai-chezan** [comment]
It's the `Disable Notification` option.

**Comment by micgrivas** [comment]
But I want to keep the calendar notification!!  
Is there no way to keep only the Calendar notifications?
