### ISSUE TITLE
Calendar event reminders not working

### ISSUE THREAD

**Issue by ljmn** [mihai-chezan/owa_notifications_firefox_extension#14]
The modified css for unread email in inbox on Office365 version provided by jscher2000 worked perfectly for me but I'm afraid I don't have enough css/html skills to come up with the css that will work for the reminders detection.

The calendar events/reminders don't come up at all.  My reminder count on the tab is always showing 0 and I don't receive any pop-ups.

Can you help?

**Comment by mihai-chezan** [comment]
Hi,

Sorry for the late reply. I don't remember getting any email notification for your post so it just slipped pass me. Anyway, in case you still use the addon and have the issue try these:
* option 1
.o365cs-flexPane-unseenCount
* option 2
.o365cs-notifications-notificationPopup .o365cs-notifications-notificationHeaderText

**Comment by mihai-chezan** [comment]
I'm working on a new version (1.8.0) which could fix some issues or provide you with some predefined options regarding custom css that might fix the problem you have. You can try installing the latest 1.8.0-alpha3 (at the moment of this writing) from the Development Channel on mozilla website: https://addons.mozilla.org/en-US/firefox/addon/outlook-web-app-notifications/versions/beta

**Comment by mihai-chezan** [comment]
possible fixed by commit 67df4ea54d79c9d70d477f122c5afccdcc6aa3c4
