### ISSUE TITLE
OWA 365 (only favorit subfolders)

### ISSUE THREAD

**Issue by slaszu** [mihai-chezan/owa_notifications_firefox_extension#17]
Hi, this is great tool, in new version you added predefined selectors, but in my case correct selector for "OWA 365 (only Inbox from Favorites)" is this "div[class="_n_I3"] + div>div>div>div>div>div>span"
Best regards

**Comment by mihai-chezan** [comment]
Hi,

Thank you for mentioning this. What version of OWA do you use? The free/personal one or the enterprise one? Also, could you check issue #16 and tell me if it work also in your case?
So using this css selector:
```
#MailFolderPane\.FavoritesFolders > div:nth-child(1) .canShowFavoritesAction  > div:nth-child(1)  > div:nth-child(1)   > div:nth-child(2) span
```

**Comment by mihai-chezan** [comment]
Closing (no feedback).
