### ISSUE TITLE
Notification does not seem to work

### ISSUE THREAD

**Issue by alex4200** [mihai-chezan/owa_notifications_firefox_extension#18]
I have this extension installed on firefox 55.0.2 (64 bit) on Ubuntu 16.04 and I have a tab open with the Outlook Web App. But when a meeting is due in the OWA calendar, no notification is shown on any of the workspaces (the meeting is a repeatable event every day at the same time). 

Screenshot of settings below:

![screenshot from 2017-09-12 09-52-26](https://user-images.githubusercontent.com/12729291/30314321-ab797d28-97a0-11e7-827b-ed88a7dd6348.png)

**Comment by mihai-chezan** [comment]
Hi,

Thank you for taking the time to report this.

I'm thinking of possible two reasons this doesn't work for you:
1. You have _"Seconds to wait between checks"_ set to 60 seconds. It might be possible that this is too long and the meeting reminder goes away in the meantime (between checks). Try setting this to 1 (one second) and see if this solves your issue.
2. The _"Css selector for reminders detection"_ is not correct for your case. I see that you have selected _"OWA 2010"_. Try other options and see if this solves your issue.

**Comment by alex4200** [comment]
Hi, 

I have made the changes as you suggested, and it seems to work now. 

Maybe the README should be adjusted, especially the first paragraph in which it says 'No configuration needed'. Just a suggestion...

Thanks

**Comment by mihai-chezan** [comment]
Could you tell me which option fixed your issue? Was is the _"Seconds to wait between checks"_ or the _"Css selector for reminders detection"_ ? In case it was the css, which option worked for you?

Related with the 'No configuration needed' from Readme, the default for checks is one second and the css selector is on Auto. So by default when you install it, it should work. But, if it doesn't work, or if you want to customize it, there is the option to do that. But I'll try to think to reformulate that part from Readme.

**Comment by alex4200** [comment]
I set the _"Seconds to wait between checks"_ to 1 as suggested and selected _"Css selector for reminders detection"_ to _auto_.  I do not remember to have changed the latter setting, but most probably that led to the problem in the first place...

**Comment by mihai-chezan** [comment]
Thank you for the info.
