### ISSUE TITLE
Count missing from the Favicon/icon on the tab

### ISSUE THREAD

**Issue by ziffusion** [mihai-chezan/owa_notifications_firefox_extension#21]
The addon doesn't seem to put the mail count on the icon on the tab.

This is with Firefox Quantum 61.0.2.

**Comment by mihai-chezan** [comment]
Could you tell me the what OWA are you using? And maybe if you could add some screenshot with the issue.

>ziffusion replied to my question with this comment:
```
The attached snapshot shows the notification for 1 new email in the lower right corner.
But the count is not showing up in the tab fav icon. The OWA tab is the 3rd from the top left.

I am using the OWA for my work email. See url below. What else would you like me to tell you about the OWA that I am using?
```
I had to delete the comment because it contained potential private information.

**Comment by ziffusion** [comment]
The attached snapshot shows the notification for 1 new email in the lower right corner.
But the count is not showing up in the tab fav icon. The OWA tab is the 3rd from the top left.

I am using the OWA for my work email. See url below. What else would you like me to tell you about the OWA that I am using?

https://email.doble.com/owa/#path=/mail

![owa](https://user-images.githubusercontent.com/341389/44288712-40e21d80-a23f-11e8-9ebd-87fac6b8da52.PNG)

**Comment by mihai-chezan** [comment]
Could you also tell me the css selectors you are using (it's in the extension preferences)

**Comment by ziffusion** [comment]
I haven't changed the defaults. It says "Auto" for all the three Css selectors.

**Comment by mihai-chezan** [comment]
Ok, I will look into it.
One more question: was it working before with a previous Firefox version?

**Comment by ziffusion** [comment]
I just installed the addon this morning.

**Comment by ziffusion** [comment]
I am a software developer myself (not Firefox though). But I can help you debug this if you like. I can run the addon debugger etc.

**Comment by mihai-chezan** [comment]
Well the bug seems strange to me at the moment because the notification shows up but not the fax icon and document title.

The code that get's executes is:
```
function checkForNewMessages() {
  let newUnreadEmailsCount = countUnreadEmails();
  let newVisibleRemindersCount = countVisibleReminders();
  let newChatNotificationsCount = countChatNotifications();
  let noChange = (newUnreadEmailsCount === unreadEmailsCount) && (newVisibleRemindersCount === visibleRemindersCount)
	  && (newChatNotificationsCount === chatNotificationsCount);
  if (noChange) {
	return;
  }
  if (prefs.updateFavIcon) {
    setFavicon(newUnreadEmailsCount + newVisibleRemindersCount + newChatNotificationsCount);
  }
  if (prefs.updateDocumentTitle) {
    setDocumentTitle(newUnreadEmailsCount, newVisibleRemindersCount, newChatNotificationsCount);
  }
  if (newUnreadEmailsCount > unreadEmailsCount) {
	triggerNotification("email", buildEmailNotificationMessage(newUnreadEmailsCount - unreadEmailsCount));
  }
```

In the extension preferences do you have the update fav icon and document title checked?

**Comment by ziffusion** [comment]
Yes, both are checked.

![image](https://user-images.githubusercontent.com/341389/44289462-560c7b80-a242-11e8-9750-9b88380bd24a.png)

**Comment by mihai-chezan** [comment]
If you could then run the addon debugger and set a breakpoint on the checkForNewMessages and see why the icon and doc title don't get executes that would be great. Thank you.

**Comment by ziffusion** [comment]
For some reason both prefs.updateFavIcon and prefs.updateDocumentTitle are undefined.

**Comment by mihai-chezan** [comment]
Could you try to uncheck them in the extension preferences, then click Save then check them, then click Save again. Then open a new tab with OWA and see if it works.

**Comment by ziffusion** [comment]
That seems to have fixed it. Thanks!

Any idea why the to members were not initalized at first?

**Comment by mihai-chezan** [comment]
It is possible that it's a bug, especially considering this was a fresh install of the extension. 
I'll check (do a fresh install on my Firefox).

**Comment by mihai-chezan** [comment]
It's a bug introduced when I migrated to WebExtensions API .
Before there was a package.json where each preference had defined a default value but migrating to WebExtensions API that was lost (only those that already had the extension had the preferences migrated  correctly).

I will push a fix. Thank you for your help.

**Comment by mihai-chezan** [comment]
I had to delete the comment with the screenshot because it contained potential private information. (I've edited my question comment to include your response but w/o the screenshot)

**Comment by ziffusion** [comment]
Great! And thanks for deleting the snapshot. Thanks for the very useful add-on. Wonder why they don't build this right into OWA.

Also - if you get around to it, it would be nice to overlay the count on the actual OWA favicon (just like gmail) instead of the blue background.

**Comment by mihai-chezan** [comment]
I was asking myself the same think. They should add notification into owa.

About the overlay: I do remember trying but the problem I had was that the count was not very visible with the overlay. So that's why I chose to use a solid background so the count is more visible that way.
