### ISSUE TITLE
Addon shows multiple identical notification

### ISSUE THREAD

**Issue by rnestler** [mihai-chezan/owa_notifications_firefox_extension#22]
I get multiple identical notifications every "Reminder snooze time". I think this is because the notification in https://github.com/mihai-chezan/owa_notifications_firefox_extension/blob/e409561a324b68656789f7d343b2b49961f43b37/src/background.js#L11 hasn't an id set (https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/notifications/create#Syntax).

**Comment by mihai-chezan** [comment]
Hi,

What value do you have set up for "Reminder snooze time" ?

**Comment by rnestler** [comment]
> What value do you have set up for "Reminder snooze time" ?

2

**Comment by mihai-chezan** [comment]
Well that might be the problem. 
2 seconds might be too small, try 5 seconds so that the previous notification has time to disappear before the new one shows. That is, if you want to have them show up almost continuously until you dismiss the reminders from owa. Otherwise, you could set bigger value, like 60 seconds (every minute, the addon will check is there are reminders and show a notification).

**Comment by rnestler** [comment]
The thing is the notification only shows up for ~4s so I'll miss it most of the time. Best would be if it would stay until I click it away and if it would provide a way to jump to the OWA tab when I click on it. But I guess this is not possible due to the limited notification API.

**Comment by mihai-chezan** [comment]
I understand. In that case, what about setting the value to 5s?
About the on click to jump to the tab... it might be possible. I need to check.

**Comment by mihai-chezan** [comment]
About clicking on the notification the API has this but Firefox doesn't implement it.

**Comment by craigneasbey** [comment]
Hi, 

I have had this issue too.  I changed the delayBetweenReminders value to 0 to disable it as suggested in the options but it just repeats continually. It appears 0 does not evaluate to false in this if statement in content-script.js

```
  if (prefs.delayBetweenReminders) {
    remindersTimer = setInterval(notifyReminders, prefs.delayBetweenReminders * 1000);
  }
```

Am I reading this right?  Should this be fixed or should the line "Set this to zero to disable it" be removed from the options please?

Happy to create another issue if needed.

thanks,
Craig

**Comment by mihai-chezan** [comment]
In javascript 0 evaluates to false.
In your case it must be something else. What happens if you set it to 10? Do you get a reminder every 10 seconds?

**Comment by craigneasbey** [comment]
Hi @mihai-chezan , 

I have debugged the code and it still enters the if block.  I think it was a string "0" which evaluates true. I am only entering 0 into the "Reminder snooze time" option.

thanks

**Comment by mihai-chezan** [comment]
That is weird. I'll take a look tomorrow and let you know.

**Comment by craigneasbey** [comment]
Thanks

**Comment by mihai-chezan** [comment]
I have identified the problem and I'll be releasing a fix soon.
Thank you for your help.

**Comment by craigneasbey** [comment]
Thanks
