### ISSUE TITLE
'The new Outlook' doesn't use /owa in path

### ISSUE THREAD

**Issue by damienpontifex** [mihai-chezan/owa_notifications_firefox_extension#24]
Using Office 365 and enabling the toggle for 'The New Outlook' the inbox now has the path of https://outlook.office365.com/mail/inbox

Is it still possible to use this extension given this change? No idea if this is a permanent URL change or part of some preview, but would be great to support.

**Comment by mihai-chezan** [comment]
Thank you for reporting this. 
The extension won't work with this new url, I would need to do a release for this. See:
https://github.com/mihai-chezan/owa_notifications_firefox_extension/blob/ec1b3e1ad52c3042d3d17597ce68bb286172c0fa/src/manifest.json#L17

It is however very possible that they also updated the interface and if that is the case I would also need to update the code for new email detection. 
I will take a look when I get some free time.

**Comment by alex-pat** [comment]
I have same issue, in my case path is `https://outlook.office.com/mail/inbox`

**Comment by cars10w** [comment]
Same here. :-)

**Comment by shanesm** [comment]
mihai-chezan - we sure hope you find some time to get your wonderful extension working with the new outlook - (https://outlook.office.com/mail/inbox). Thanks in advance!

**Comment by mihai-chezan** [comment]
Added outlook.office365.com and outlook.office.com urls to trigger the extension to load with commit 411cbb747d4743b076a925d70c4a7e81ddc8f566
This change has been released with new version 1.9.5.
Unfortunately I don't have access any more to  office365 so I can't test the css if they work so I hope it works for you guys.

**Comment by cars10w** [comment]
I am afraid that I need to report that it does not work for me.. Using 1.9.5 and https://outlook.office.com/mail/

**Comment by kschoelhorn** [comment]
Reminders work for me on https://outlook.office365.com/mail with `[data-storybook="reminder"]` on `Auto`. Haven't tested emails.

**Comment by cars10w** [comment]
Works for me for reminders as well, but not for emails.

**Comment by bsferrazza-avnera** [comment]
Can you also add *://*/ecp/*?

My company's owa url uses /ecp/ which is Exchange Control Panel, another common url directory. Thank you.

**Comment by jacklovell** [comment]
Emails work for me, after slightly modifying  the CSS selector. I used `outlook.live.com beta (just Favorites inbox)` but modified the CSS selector from `[title="Favorites"]` to `[title="Favourites"]` as I'm using British English.
