### ISSUE TITLE
how to install offline

### ISSUE THREAD

**Issue by nicolasdemarchi** [mihai-chezan/owa_notifications_firefox_extension#25]
Hello! I have no access to internet. Any way to install (a signed version) offline? 

Currently I'm using about:debugging to add the .zip I downloaded from this repo

**Comment by mihai-chezan** [comment]
Can't you download the addon (signed) from Mozilla ?
https://addons.mozilla.org/firefox/downloads/file/1690160/outlook_web_app_notifications-1.9.5-fx.xpi
