### ISSUE TITLE
notifications stopped working with updated OWA

### ISSUE THREAD

**Issue by nerijusk** [mihai-chezan/owa_notifications_firefox_extension#29]
Around Aug-Sep 2019 Microsoft updated OWA. With these updates extension notifications have disappeared. Initially it was possible to turn on the old OWA look'n'feel in OWA settings, but this option has been removed and the new interface is the only one available.

**Comment by mihai-chezan** [comment]
Hi,
Thank you for raising this issue. 
I will look into this asap.
Are we talking about the free public 
https://outlook.live.com/owa/
?

**Comment by nerijusk** [comment]
Sorry for not including relevant information. The issue is on Office365. Mail link is https://outlook.office.com/mail/inbox. Calendar link is https://outlook.office.com/calendar/view/week, but it can also end in one of [day|week|workweek|month].

**Comment by mihai-chezan** [comment]
So that is not the free owa and unfortunately I don't have access to it (I don't have an Office 365 account anymore).

**Comment by nerijusk** [comment]
is there anything i can try extracting from using office365 owa interface?

**Comment by mihai-chezan** [comment]
Yes, there is !
When you have at least a new unread email (you can select an existing email and mark it unread), in the folder panel (the one on the left containing the Inbox and the other folders), you will see the number of unread emails being displayed. Right click on it and select "Inspect element" option. A panel will open up with the html of the current page and the element containing the unread emails will be selected. You then right click on it and select "Copy-> CSS Selector" and then reply here with the content of the copied css selector.

**Comment by mihai-chezan** [comment]
For example, the css selector for the button "Comment" on this page is "div.bg-gray-light:nth-child(2) > button:nth-child(1)"

**Comment by AndSab** [comment]
CSS selector for unread counter looks like this `.VvaKbiG13j8JUB9fmPlUP`  and probably is an automatically generated one.

Full CSS path of that span is 

```
html body.ms-font-s.disableTextSelection div#app div.ms-Fabric._2HTFmaDIVHVbnIkwPM9srx.root-40 div._3KAPMPOz8KsW24ooeUflK2 div._2jR8Yc0t2ByBbcz_HIGqZ4 div._1TpU2KF6f_EeQiytBaYj8I div._25oA4qBLP_b6P080cw5s2H.css-38 div._1_iewjAgd8BRIHH3zHMH1V div.HWDcgTrRzWs8-3feN1tMa div.ms-FocusZone.css-57._2uIW6I_1SKuzoss6jjAHdO._5okTAp2hNSQWz1YIB0_1F._1F5fN7hNCW953fRaaUKE_L.customScrollBar.disableTextSelection div div._1ci7WbFYZSInPwqVpr89mC div div._21GIf9eXgdq_YZiQrKnLYC.qDw7SZ9r6S7r0_qZS1aIG span._3Jn_7Iv4SwMTMOPJiydZLa span.VvaKbiG13j8JUB9fmPlUP._3znt5bn-HsoKLR4JiGNhgk
```

But not sure if even this will help

**Comment by mihai-chezan** [comment]
Indeed, doesn't look like we can work with this.
What about the element itself, can you copy paste here the html content for it?
So use `Copy->Outer HTML`.
The html for the Comment button is:
```
<button type="submit" class="btn btn-primary" data-disable-with="" data-disable-invalid="">
          Comment
      </button>
```

**Comment by AndSab** [comment]
```
<span class="_3Jn_7Iv4SwMTMOPJiydZLa">
  <span class="VvaKbiG13j8JUB9fmPlUP _3znt5bn-HsoKLR4JiGNhgk">
    1
    <span class="screenReaderOnly">unread</span>
  </span>
</span>
```
Maybe that child span for screen readers could be used :thinking:

**Comment by mihai-chezan** [comment]
I don't think I can solve this with a css selector so I will have to do it from js.
If you execute 
```
document.querySelectorAll("span span span.screenReaderOnly").length
```
from console what do you get?

**Comment by mihai-chezan** [comment]
And if you could also execute this and tell me the result:
```
Array.from(document.querySelectorAll("span span span.screenReaderOnly")).filter(e => e.textContent==='unread').map(e => e.previousSibling.textContent).join();
```

**Comment by AndSab** [comment]
`document.querySelectorAll("span span span.screenReaderOnly").length`

Return the number of direcotires that have unread messages

`Array.from(document.querySelectorAll("span span span.screenReaderOnly")).filter(e => e.textContent==='unread').map(e => e.previousSibling.textContent).join();`
returns
`"2,3"` 

I had two directories with 2 and 3 unread messages in them

**Comment by mihai-chezan** [comment]
I've prepared a new version 1.9.6 which should fix this problem.
Unfortunately uploading new addons fails for me at the moment, there is a ticket at Mozilla that tracks this issue: https://github.com/mozilla/addons/issues/1108

**Comment by mihai-chezan** [comment]
Now the upload works, so you should get the new version soon (you can manually force the update by going to the `Outlook Web App Notifications` extension and select `Check for updates`).

**Comment by nerijusk** [comment]
It works now for Office365 OWA. Thanks a lot for the update!

**Comment by mihai-chezan** [comment]
Thank you all for helping me to fix this.
