### ISSUE TITLE
Distinguish mail folders

### ISSUE THREAD

**Issue by nilskp** [mihai-chezan/owa_notifications_firefox_extension#3]
Generally, I would prefer to only get notifications (and message count in tab) for my Inbox. I get a crap-load of emails from various services, which are filtered into another folder.

As it is right now, I get constant notifications, which drowns the important ones.

Not sure how hard this will be, but generally Outlook Web App gives me a sound notification when the Inbox is hit, but nothing when the message is filtered, so this may be a clue on how to solve this.

**Comment by mihai-chezan** [comment]
With commit 7f812e0 you can tweak the css selector for unread email detection to something like "[fldrnm='Inbox'] + #spnUC #spnCV" which in case of OWA 2010 will only count unread emails from Inbox folder.

**Comment by eddy-geek** [comment]
I am not sure where to document this, so here is a selector that worked for me for a recent version of OWA (X-OWA-ClientBuildVersion:"15.0.847.41"):

```
span[title="Inbox"] ~ ._n_07
```

**Comment by mihai-chezan** [comment]
@eddy-geek Thank you for this information. I have updated the Readme to include this information.
