### ISSUE TITLE
Bad counter ?

### ISSUE THREAD

**Issue by metal3d** [mihai-chezan/owa_notifications_firefox_extension#6]
See the screenshot, it seems that counter is not good:
![capture d ecran de 2015-07-10 10-17-47](https://cloud.githubusercontent.com/assets/100080/8614730/f5fd5742-26ec-11e5-800e-497cb0e96ef0.png)

As you can see, it's written that I've got 3 messages in favicon, but I've only one unread message.

That ok for the schedule counter. Only the mail counter is not ok.

**Comment by mihai-chezan** [comment]
Try this: go to owa addon preferences and put the following value for "Custom css selector for unread email detection": `#mailtree div.trNdHl:not(.trNdDelFol) #spnUC #spnCV`
Let me know if it works.

**Comment by quincy** [comment]
I was seeing the same issue and your suggestion fixed it.

**Comment by metal3d** [comment]
I will try it tomorow

**Comment by metal3d** [comment]
@mihai-chezan that works as expected, big thanks !
