### ISSUE TITLE
linux/ubuntu support?

### ISSUE THREAD

**Issue by seanjohnite** [mihai-chezan/owa_notifications_firefox_extension#9]
Hey,

I can't seem to get this to work with Ubuntu. No number displayed in the favicon (although it did change initially), and new emails don't seem to trigger any notifications. Is there anything else I need to configure?

-sean

**Comment by mihai-chezan** [comment]
Hi,
There should be no need for any configuration changes for this addon to work. If after installation you can't see any changes to the window/tab name and/or no changes to the favicon when new email arrives (or having unread messages) it means you have some OWA version for which the addon doesn't work out of the box.
What you could try, if you know some css, is to try and find out what css selector works for your OWA version.
Go to add-ons -> extensions -> Outlook Web App Notifications, click Preferences and edit "Custom css selector for unread emails detection".
See some of the users reviews, maybe some of their css selector will work for you:
https://addons.mozilla.org/en-US/firefox/addon/outlook-web-app-notifications/reviews/
Or read some of the closed issues here on github, maybe that will help:
https://github.com/mihai-chezan/owa_notifications_firefox_extension/issues?q=is%3Aissue+is%3Aclosed

**Comment by seanjohnite** [comment]
Thanks for the reply! I think I almost have it working. X-OWA-Version is 15.1.443.13.

Does the script count the number of items that match the CSS selector? Or does it rather look at the inner text node that contains the number next to "Inbox"?

**Comment by seanjohnite** [comment]
Excellent! I put `._n_x4` into the CSS selector box, and it seems to work.

Folder specificity (at least for me) is obtained with `span[title="Inbox"]~._n_A4 ._n_x4`

**Comment by mihai-chezan** [comment]
Glad to hear you found the right css for your version.
To answer your question about how the css selector is used: for each matched node, the inner html is considered to be a number, and the count is the sum of these numbers.
The code looks like this:

```
var nodes = document.querySelectorAll(prefs.cssForUnreadEmailsDetection);
var count = 0;
for (var i = nodes.length - 1; i >= 0; i--) {
   count += extractNumber(nodes[i].innerHTML);
}

function extractNumber(text) {
   if (text) {
      var digits = text.match(/\d/gi);
      if (digits) {
         return parseInt(digits.join(""), 10);
      }
   }
   return 0;
}
```
